use_frameworks!

target 'AnimatedTextFieldCounter_Example' do
  pod 'AnimatedTextFieldCounter', :path => '../'

  target 'AnimatedTextFieldCounter_Tests' do
    inherit! :search_paths

    
  end
end
